version: '3.8'
services:
  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    env_file:
      - ./payment-service/.env

  notification-service:
    build: ./notification-service
    ports:
      - "3002:3002"
    env_file:
      - ./notification-service/.env

